version: "3.9"

services:
  backend:
    build: ./oven_earth_back/product_service
    volumes:
      - ./oven_earth_back/product_service:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./oven_earth_front
    ports:
      - "3000:3000"
    depends_on:
      - backend