# Generated by Django 5.2 on 2025-05-17 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_order_status_alter_orderitem_product'),
        ('product_management', '0003_bakeryitem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_management.bakeryitem'),
        ),
    ]
