# Generated by Django 5.2 on 2025-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bakery_image/'),
        ),
    ]
