# Generated by Django 5.2 on 2025-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_bakeryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryitem',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
